name: style
on:
  pull_request:
  push:
    branches: [ jazzy ]
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ['jazzy']
    container:
      image: ros:${{ matrix.distro }}-ros-base
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: uncrustify
      run: /ros_entrypoint.sh ament_uncrustify rmw_zenoh_cpp/ zenoh_security_tools/
    - name: cpplint
      run: /ros_entrypoint.sh ament_cpplint rmw_zenoh_cpp/ zenoh_security_tools/
